version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: bank_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bank_app
      MYSQL_USER: bank_user
      MYSQL_PASSWORD: bank_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: bank_backend
    environment:
      DB_HOST: db
      DB_USER: bank_user
      DB_PASSWORD: bank_password
      DB_NAME: bank_app
      DB_PORT: 3306
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bank_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: